-- Insert additional 10 Deutsche Telekom products to reach 50 total
INSERT INTO degoudse.products (id, name, description, category, "createdAt", "updatedAt") VALUES (2040, 'T-Systems AI Factory', 'Advanced Analytics & AI solution from T-Systems', 'Analytics & AI', NOW(), NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO degoudse.products (id, name, description, category, "createdAt", "updatedAt") VALUES (2041, 'Telekom Quantum Communication', 'Advanced Security solution from Deutsche Telekom', 'Security', NOW(), NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO degoudse.products (id, name, description, category, "createdAt", "updatedAt") VALUES (2042, 'T-Systems Blockchain Services', 'Advanced Digital & Application solution from T-Systems', 'Digital & Application', NOW(), NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO degoudse.products (id, name, description, category, "createdAt", "updatedAt") VALUES (2043, 'Telekom Edge Computing Platform', 'Advanced Cloud & Hosting solution from Deutsche Telekom, T-Systems', 'Cloud & Hosting', NOW(), NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO degoudse.products (id, name, description, category, "createdAt", "updatedAt") VALUES (2044, 'T-Systems Cybersecurity Operations Center', 'Advanced Security solution from T-Systems', 'Security', NOW(), NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO degoudse.products (id, name, description, category, "createdAt", "updatedAt") VALUES (2045, 'Telekom 5G Enterprise', 'Advanced Connectivity & Network solution from Deutsche Telekom', 'Connectivity & Network', NOW(), NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO degoudse.products (id, name, description, category, "createdAt", "updatedAt") VALUES (2046, 'T-Systems Digital Workspace', 'Advanced Digital Workplace solution from T-Systems', 'Digital Workplace', NOW(), NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO degoudse.products (id, name, description, category, "createdAt", "updatedAt") VALUES (2047, 'Telekom Cloud Backup Suite', 'Advanced Cloud & Hosting solution from Deutsche Telekom, T-Systems', 'Cloud & Hosting', NOW(), NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO degoudse.products (id, name, description, category, "createdAt", "updatedAt") VALUES (2048, 'T-Systems Healthcare Cloud', 'Advanced Industry Solutions solution from T-Systems', 'Industry Solutions', NOW(), NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO degoudse.products (id, name, description, category, "createdAt", "updatedAt") VALUES (2049, 'Telekom Smart Building Solutions', 'Advanced IoT & M2M solution from Deutsche Telekom, T-Systems', 'IoT & M2M', NOW(), NOW()) ON CONFLICT (id) DO NOTHING;
