-- OKR Plan Integration SQL
-- Generated from Excel file with 12 key results across 4 objectives

-- Insert OKR Plan metrics (1 batches of up to 20 each)

-- Batch 1 of 1
INSERT INTO degoudse.okr_metrics (name, description, target_value, measure_unit, currency_type, timeframe, frequency, due_date, is_muted, is_archived, is_shared, hierarchy, tags, created_at, updated_at, created_by) VALUES 
('Achieve combined DT-product bookings via Cancom', '1. Grow Joint Revenue - Achieve combined DT-product bookings via Cancom', 12000000, 'currency', 'EUR', 'quarterly', 'monthly', '2025-09-30', false, false, true, 'strategic', '{okr_plan,1__grow_joint_revenue}', NOW(), NOW(), 1),
('Close new cross-sell deals (> 0.5 M € each)', '1. Grow Joint Revenue - Close new cross-sell deals (> 0.5 M € each)', 8, 'count', NULL, 'quarterly', 'monthly', '2025-09-30', false, false, true, 'strategic', '{okr_plan,1__grow_joint_revenue}', NOW(), NOW(), 1),
('Increase renewals rate on existing joint customers', '1. Grow Joint Revenue - Increase renewals rate on existing joint customers', 95, 'percentage', NULL, 'quarterly', 'monthly', '2025-09-30', false, false, true, 'strategic', '{okr_plan,1__grow_joint_revenue}', NOW(), NOW(), 1),
('Generate qualified DT-product opportunities (min. 50 K € ACV)', '2. Expand Pipeline Quality & Quantity - Generate qualified DT-product opportunities (min. 50 K € ACV)', 50, 'count', NULL, 'quarterly', 'monthly', '2025-08-31', false, false, true, 'strategic', '{okr_plan,2__expand_pipeline_quality___quantity}', NOW(), NOW(), 1),
('Maintain an average opportunity win rate', '2. Expand Pipeline Quality & Quantity - Maintain an average opportunity win rate', 30, 'percentage', NULL, 'quarterly', 'monthly', '2025-08-31', false, false, true, 'strategic', '{okr_plan,2__expand_pipeline_quality___quantity}', NOW(), NOW(), 1),
('Build new reference architectures for top-3 verticals', '2. Expand Pipeline Quality & Quantity - Build new reference architectures for top-3 verticals', 5, 'count', NULL, 'quarterly', 'monthly', '2025-08-31', false, false, true, 'strategic', '{okr_plan,2__expand_pipeline_quality___quantity}', NOW(), NOW(), 1),
('Complete joint sales trainings on Cloud, Security, and IoT', '3. Deepen Technical & GTM Alignment - Complete joint sales trainings on Cloud, Security, and IoT', 3, 'count', NULL, 'quarterly', 'monthly', '2025-07-31', false, false, true, 'strategic', '{okr_plan,3__deepen_technical___gtm_alignment}', NOW(), NOW(), 1),
('Run co-branded webinars/events with ≥ 200 attendees each', '3. Deepen Technical & GTM Alignment - Run co-branded webinars/events with ≥ 200 attendees each', 2, 'count', NULL, 'quarterly', 'monthly', '2025-07-31', false, false, true, 'strategic', '{okr_plan,3__deepen_technical___gtm_alignment}', NOW(), NOW(), 1),
('Launch joint “DT-Cancom Success Pack” on Partner Portal', '3. Deepen Technical & GTM Alignment - Launch joint “DT-Cancom Success Pack” on Partner Portal', 0, 'units', NULL, 'quarterly', 'monthly', '2025-09-15', false, false, true, 'strategic', '{okr_plan,3__deepen_technical___gtm_alignment}', NOW(), NOW(), 1),
('Implement bi-weekly deal-review cadence', '4. Improve Operational Excellence & Satisfaction - Implement bi-weekly deal-review cadence', 6, 'count', NULL, 'quarterly', 'monthly', '2025-09-30', false, false, true, 'strategic', '{okr_plan,4__improve_operational_excellence___satisfaction}', NOW(), NOW(), 1),
('Achieve Net Promoter Score among Cancom-supported DT accounts', '4. Improve Operational Excellence & Satisfaction - Achieve Net Promoter Score among Cancom-supported DT accounts', 8, 'count', NULL, 'quarterly', 'monthly', '2025-09-30', false, false, true, 'strategic', '{okr_plan,4__improve_operational_excellence___satisfaction}', NOW(), NOW(), 1),
('Resolve support escalations within 24 hours', '4. Improve Operational Excellence & Satisfaction - Resolve support escalations within 24 hours', 90, 'percentage', NULL, 'quarterly', 'monthly', '2025-09-30', false, false, true, 'strategic', '{okr_plan,4__improve_operational_excellence___satisfaction}', NOW(), NOW(), 1);
